## Basic Numpy

In [1]:
import numpy as np

arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr = np.full((3, 3), fill_value=True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [4]:
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [5]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [8]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [9]:
import numpy as np


def maxx(x, y):
    if x >= y:
        return x
    else:
        return y


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [10]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

print("Result", np.where(a<b,b,a))

Result [6 7 9 8 9 7 5]


## Image Processing

In [12]:
import matplotlib.image as mpimg
img = mpimg.imread("dog.jpeg")
gray_img = (np.max(img[:, :, :3], axis=2) + np.min(img[:, :, :3], axis=2)) / 2
gray_img[0, 0]

102.5

In [13]:
import matplotlib.image as mpimg
img = mpimg.imread("dog.jpeg")
gray_img_02 = (np.average(img[:, :, :3], axis=2))
gray_img_02[0, 0]

107.66666666666667

In [14]:

import matplotlib.image as mpimg
img = mpimg.imread("dog.jpeg")
gray_img_03 = (np.dot(img[:, :, :3], [0.21, 0.72, 0.07]))
gray_img_03[0, 0]

126.22999999999999

## Phân tích dữ liệu dạng bảng

In [15]:

import pandas as pd
df = pd.read_csv("advertising.csv")
data = df.to_numpy()

In [16]:
# select 3rd column
max = np.max(data[:, 3])
print(max)
# get max index
max_index = np.argmax(data[:, 3])
print(max_index)

27.0
175


In [17]:
np.average(data[:, 0])

147.0425

In [18]:
np.size(np.where(data[:, 3] >= 20))

40

In [19]:
index_list = np.argwhere(data[:, 3] >= 15)
sum = 0
for i in index_list:
    sum += data[i, 1]
average = sum / np.size(index_list)
print(average)

[26.22293578]


In [60]:
newspaper_avg = np.average(data[:, 2])
sum = 0
for i in range(np.size(data, 0)):
    if data[i, 2] > newspaper_avg:
       sum += data[i, 3]
sum

1405.1000000000004

In [76]:
# fill by condition
sales_avg = np.average(data[:, 3])
print(sales_avg)
arr = data[:, 3]
new_arr = []
for i in range(np.size(arr)):
    if arr[i] > sales_avg:
        new_arr.append('Good')
    elif arr[i] < sales_avg:
        new_arr.append('Bad')
    else:
        new_arr.append('Average')
new_arr[7:10]

15.130500000000001


['Bad', 'Bad', 'Good']

In [74]:
import pandas as pd

# Đọc dữ liệu từ file CSV
df = pd.read_csv('advertising.csv')

# Chuyển đổi dữ liệu thành mảng numpy
data = df.to_numpy()

# Tính giá trị trung bình của cột Sales
mean_sales = data[:, 3].mean()
# Tạo mảng scores
scores = []

for sale in data[:, 3]:
    if sale > mean_sales:
        scores.append('Good')
    elif sale < mean_sales:
        scores.append('Bad')
    else:
        scores.append('Average')

# In ra kết quả scores[7:10]
print(scores[7:10])


15.130500000000001
['Bad', 'Bad', 'Good']
